= Creating and Customizing Workspaces in Red Hat OpenShift DevSpaces
:navtitle: Home

== Introduction

Welcome to this quick course on _Creating and Customizing Workspaces in Red Hat OpenShift DevSpaces_.
This course is the `fourth` in a series of `five` courses about Red Hat OpenShift DevSpaces:

. https://redhatquickcourses.github.io/devspaces-intro[Introduction to Red Hat OpenShift Dev Spaces^]
. https://redhatquickcourses.github.io/devspaces-admin[Red Hat OpenShift Dev Spaces Administration^] 
. https://redhatquickcourses.github.io/devspaces-security[Securing Access to Red Hat OpenShift Dev Spaces^]
. Creating and Customizing Workspaces in Red Hat OpenShift Dev Spaces (_This course_)
. Configuring Plugins in Red Hat OpenShift Dev Spaces (_Under Development_)

This course covers how to create, customize, and manage `Workspaces` on Dev Spaces.

NOTE: The hands-on labs for this course have been tested on *Red Hat OpenShift Dev Spaces 3.16*. The labs should mostly work on minor update releases of Dev Spaces. If you encounter any issues, please open a GitHub issue in the course repository.

== Course Objectives

The overall objectives of this course include:

* Create and manage workspaces using the Dev Spaces dashboard
* Using the Universal Developer Image (UDI) in workspaces
* Customizing the Dev Spaces dashboard
* Configuring Kubedock to build containers in workspaces
* Configuring IDEs in workspaces
* Creating Devfiles
* Creating a custom base container image for workspaces

== Course Prerequisites

* You must complete the first three courses in the learning path covering the basics of Dev Spaces, its administration, and security
* Basic knowledge of OpenShift (or Kubernetes) administration
* Knowledge of building Docker or Podman containers
* Deploying container images on OpenShift or Kubernetes
* OpenShift or Kubernetes User and Role Administration

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Ravi Srinivasan
* Rutuja Deshmukh
* Anna Swicegood
* Caitlyn Rymarchyk
* Anton Giertli
* Anatolii Bazko

== Classroom Environment

You must continue to use the classroom you provisioned for Dev Spaces in the second course (__Red Hat OpenShift Dev Spaces Administration__) of the learning path. You must have a valid installation of Dev Spaces using any of the approaches taught in the second course.