# Creating a Devfile

A devfile is a simple plain text YAML file with a specific structure.

== Key Components of a Devfile:

Projects:: Lists the repositories that need to be cloned or initialized for the development environment.
Components:: Defines various containers or plugins (like databases, runtimes) needed in the development workspace.
Commands:: Specifies tasks or actions such as "build," "run," and "test" that can be executed within the environment.
Events:: Allows automation of tasks at certain stages, such as before starting or after stopping a container.

An example Devfile, defining a development environment for a simple Node.js application that communicates with a PostgreSQL database is provided below:

[source,yaml,subs=+quotes]
----
schemaVersion: 2.2.0

metadata: <1>
  name: nodejs-sample-app
  version: 1.0.0
  description: Devfile for a sample Node.js application
  icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/node-js.svg
  tags:
    - Node.js
    - Express
    - ubi8

projects: <2>
  - name: nodejs-app
    source:
      type: git
      location: "https://github.com/some-repository/nodejs-app.git"
      branch: main

components:
  - name: nodejs
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest <3>
      memoryLimit: 512Mi
      mountSources: true
      command: ["npm"]
      args: ["start"]
      volumeMounts: <4>
        - name: node-modules
          path: "/projects/node_modules"
      endpoints: <5>
        - name: "app"
          targetPort: 3000
          exposure: public
          protocol: http

  - name: postgres-db 
    container:
      image: "postgres:13" <6>
      memoryLimit: 512Mi
      endpoints:
        - name: postgres
          exposure: internal
          targetPort: 5432
          attributes:
            discoverable: 'true'
      env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: devdb
      volumeMounts:
        - name: db-data
          path: "/var/lib/postgresql/data"

commands: <7>
  - id: install
    exec:
      component: nodejs
      commandLine: "npm install"
      workingDir: /projects/nodejs-app
      group:
        kind: build
        isDefault: true

  - id: run
    exec:
      component: nodejs
      commandLine: "npm run dev"
      workingDir: /projects/nodejs-app
      group:
        kind: run
        isDefault: true

  - id: test
    exec:
      component: nodejs
      commandLine: "npm test"
      workingDir: /projects/nodejs-app
      group:
        kind: test
        isDefault: true

events: <8>
  preStart:
    - install
  postStop:
    - id: cleanup
      exec:
        component: nodejs
        commandLine: "npm run clean"

volumes: <9>
  - name: node-modules
    size: 1Gi
  - name: db-data
    size: 1Gi
----

<1> Devfile metadata. Name, description, tags and an icon declaration.
<2> Project details and location of Git repository
<3> Container image to be loaded in the Workspace. In this case, we load the UDI since it contains a Node.js runtime.
<4> Mount data volumes inside the container. These reference volume names declared in the `volumes` section.
<5> Network endpoints to be exposed in the workspace.
<6> Declaration of the PostgreSQL database container, along with volume mounts, resource limits and some environment variables used by the container.
<7> Commands that can be run in this workspace. In this case, to install NPM packages, run Node.js and run tests. These are made available in the IDE as `Tasks` in the `Task` menu.
<8> Event hooks. These commands are run at startup and shutdown of the workspace.
<9> Volume name and size declarations. These are mounted in the `volumeMounts` section of the devfile.

NOTE: Red Hat OpenShift Dev Spaces is expected to work with most of the popular images defined in the components section of a Devfile. For production purposes, it is recommended to use one of the Universal Base Images (UBI) from Red Hat as a base image for defining the developer environment.

IMPORTANT: Some images cannot be used as is for defining a developer environment since `Visual Studio Code - Open Source` cannot be started with missing `openssl` and `libbrotli` packages. Missing libraries should be explicitly installed inn the `Dockerfile` for the container, that is using `RUN yum install compat-openssl11 libbrotli`.

== References

* https://registry.devfile.io/viewer[Public Community Devfile Registry^]