= Kubedock

*Kubedock* is a tool that allows developers to run containers inside OpenShift clusters as if they were running locally on a workstation. It bridges the gap between local container-based development workflows and cloud-native environments, helping to replicate the local developer experience inside an OpenShift cluster.

This is particularly useful in development environments like Dev Spaces, which is designed for cloud-native, OpenShift-based development.

IMPORTANT: Kubedock is meant as a temporary stop-gap fix to run "containers inside containers". OpenShift 4.17+ will allow this functionality to work natively without the need for Kubedock.

== How Kubedock Works

Kubedock intercepts Linux container API calls made by developers or development tools and translates these into OpenShift-native constructs (such as Pods, Deployments, etc.).
When a developer issues a `podman run` command, instead of using the local Podman engine, Kubedock converts these commands to OpenShift resources, allowing the containers to run in the OpenShift cluster.

Kubedock manages the lifecycle of these resources, making the OpenShift environment behave more like a local Podman instance from the developer’s perspective.

image::kubedock-diagram.svg[title=Kubedock]

== Key Features of Kubedock:

* *Podman Workflow:* Developers can use familiar Podman commands (podman run, podman build, etc.) while developing in an OpenShift environment, maintaining their existing workflows. Instead of learning OpenShift-specific tools and syntax, they can continue using Podman commands that are familiar to them.

* *OpenShift Integration:* Kubedock ensures that containers run inside the OpenShift cluster, integrating seamlessly with other OpenShift services like networking, storage, and scaling, providing cloud-native capabilities. Developers get the benefits of OpenShift (scalability, orchestration, etc.) while retaining the simplicity of Podman commands. This provides a hybrid development experience that leverages the strengths of both Podman and OpenShift.

* *Devfile Compatibility:* It works with Devfiles (which Dev Spaces uses to define development environments) to enable the use of container images or commands as part of the developer’s workspace, while all underlying infrastructure runs in OpenShift.

* *Consistency in Development and Production:* Since Kubedock runs containers inside OpenShift, the development environment more closely mirrors production environments (which are often OpenShift-based). This reduces the risk of discrepancies between local development and production behavior, improving deployment reliability.

* *No Need for a Local Podman Daemon:* In cloud-native or distributed environments (like Eclipse Che), developers may not have access to a local Podman daemon. Kubedock eliminates the need for a local Podman installation by running containers directly in OpenShift, removing platform-specific limitations.

* *Support for Complex Development Environments:* Kubedock enables the use of complex containerized environments directly in OpenShift, supporting multi-container applications, microservices, or multi-tiered setups that are easier to orchestrate in an OpenShift cluster than with standalone Podman.

* *Reduced Local Setup Complexity:* Developers using Eclipse Che in combination with Kubedock don’t need to install Podman or manage local container runtimes. Everything is managed by OpenShift, reducing the overhead of local environment setup and configuration.

IMPORTANT: The container image you want to use with Kubedock must be compliant with the https://docs.openshift.com/container-platform/4.16/openshift_images/create-images.html#images-create-guide-openshift_create-images[Openshift Container Platform guidelines^]. Otherwise, running the image with Kubedock will result in a failure even if the same image runs locally without issues.

NOTE: The `podman build -t <image> && podman run <image>` command will fail. Instead, use `podman build -t <image> && podman push <image> && podman run <image>` by first building the image, pushing it to a container registry, and then running it.

== References

* https://docs.redhat.com/en/documentation/red_hat_openshift_dev_spaces/3.16/html-single/user_guide/index#running-containers-with-kubedock[Kubedock^]

== Lab: Enabling Kubedock and Working with Containers in Workspaces

. Inspect the repository at https://github.com/rsriniva/kubedock-test[window=_blank]. Review the simple devfile at https://github.com/rsriniva/kubedock-test/blob/main/devfile.yaml[window=_blank].
+
[source,yaml,subs=+quotes]
----
schemaVersion: 2.2.0
metadata:
  name: kubedock-test
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:latest
      memoryLimit: 3Gi
      *env:
        - name: KUBEDOCK_ENABLED
          value: "true"
        - name: DOCKER_HOST
          value: 'tcp://127.0.0.1:2475'
      endpoints:
        - exposure: none
          name: kubedock
          protocol: tcp
          targetPort: 2475*
----
+
You need to add two environment variables to the devfile (`KUBEDOCK_ENABLED` and `DOCKER_HOST`). The first enabled Kubedock in the workspace, and the second indicates that the local daemon should be used for container builds. You also need to add an `endpoint` section and declare the port at which the Kubedock daemon should listen.

. Fork this repository into your own GitHub account.

. Log in to Dev Spaces as a `user``. Launch a new workspace using the Git URL https://github.com/<your_github_user>/kubedock-test.

. Once the workspace is fully loaded, open a new terminal window and verify that Podman is working correctly.
+
[source,bash,subs=+quotes]
----
$ podman info
_host:
  arch: amd64
  buildahVersion: 1.33.8
...
version:
  APIVersion: 4.9.4-rhel
...
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.4-rhel_
----

. Run a simple container using `podman run`
+
[source,bash,subs=+quotes]
----
$ podman run docker.io/hello-world
_Hello from Docker!
This message shows that your installation appears to be working correctly.
..._
----

. The repository contains a simple Dockerfile that builds a container image using a statically compiled C program (`hello`). Build the container image.
+
[source,bash,subs=+quotes]
----
$ podman build -t hello .
_STEP 1/3: FROM scratch
STEP 2/3: COPY hello /
--> a6da5afc829b
STEP 3/3: CMD ["/hello"]
COMMIT hello
--> 443fe4de6c5e
Successfully tagged localhost/hello:latest
..._
----

. Verify that the image is built successfully
+
[source,bash,subs=+quotes]
----
$ podman images
_REPOSITORY       TAG         IMAGE ID      CREATED             SIZE
localhost/hello  latest      443fe4de6c5e  About a minute ago  16.5 kB_
----
+
NOTE: If you try to run this locally-built container image, it will fail. You need to tag and push this image to an external container registry and then run it.